# Pandoc配置文件 - 微语协作平台技术手册
metadata:
  title: "微语协作平台技术手册"
  subtitle: "技术架构与部署指南"
  author: "北京微语天下科技有限公司"
  date: "2025年9月1日"

variables:
  lang: zh-CN
  mainfont: "PingFang SC"
  fontsize: 11pt
  geometry: margin=2cm
  linestretch: 1.3

metadata-files:
  - header.yaml
