# Pandoc配置文件 - 用于改善Word文档格式
metadata:
  title: "微语AI文生文解决方案"
  subtitle: "企业级会议纪要与办公文档智能生成系统"
  author: "微语科技"
  date: "2025年7月5日"

variables:
  lang: zh-CN
  mainfont: "PingFang SC"
  fontsize: 12pt
  geometry: margin=2.5cm

metadata-files:
  - header.yaml
