# 
# github：依次添加以下变量，
# 路径：Settings -> Secrets And Variables -> Actions
# SERVER_HOST / Secret：服务器公网IP
# SERVER_USERNAME / Secret：服务器用户名
# SERVER_PASSWORD / Secret：服务器密码
# SERVER_PORT / Secret：服务器端口

name: mycicd
on:
  push:
    # branches: main
    # 打标签的时候触发
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 安装nodejs
        uses: actions/setup-node@v4
      - name: 安装依赖
        run: yarn
      - name: 前端打包
        run: yarn build
        # 部署到服务器
        # https://github.com/appleboy/scp-action
      - name: 上传到服务器
        uses: appleboy/scp-action@v0.1.7
        with:
          # 服务器域名
          host: ${{ secrets.SERVER_HOST }}
          # 服务器用户名
          username: ${{ secrets.SERVER_USERNAME }}
          # 服务器密码
          password: ${{ secrets.SERVER_PASSWORD }}
          # 服务器端口22
          port: ${{ secrets.SERVER_PORT }}
          # 指定上传的文件目录(项目配置的打包目录名称)
          source: './build/*'
          # 指定上传服务器目录
          target: '/var/www/html/weiyuai/docs'
          # 解压时覆盖现有文件
          overwrite: true
          # 删除指定数量的前导路径元素
          # strip_components: 1

