name: mycicd
on:
  # 代码push的时候触发
  push:
    # main分支的时候触发
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: 检查代码
        uses: actions/checkout@v4.1.7
      - name: 安装nodejs
        uses: actions/setup-node@v4.0.3
      - name: 安装依赖
        run: yarn
      - name: 前端打包
        run: yarn build

